# F.Y.I. https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml
remote_theme: just-the-docs/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "GitHubで開く":
    - "//github.com/yuzutas0/awesome-redshift-jp"

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "トップに戻る"
footer_content: "問い合わせ先：Slackコミュニティ「<a href=\"https://datatech-jp.github.io/\">datatech-jp</a>」の「<a href=\"https://datatech-jp.slack.com/archives/C03MHCZS2GG\">#redshift</a>」チャンネル"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "このページをGitHubで編集する"
gh_edit_repository: "https://github.com/yuzutas0/awesome-redshift-jp" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-seo-tag
